#pragma checksum "..\..\..\CadSyncControl.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6F58F0F2FAF8D56FA0A56A1E0CE36B9689A4AE0E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace CadSyncPlugin {
    
    
    /// <summary>
    /// CadSyncControl
    /// </summary>
    public partial class CadSyncControl : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 300 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse StatusDot;
        
        #line default
        #line hidden
        
        
        #line 302 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush StatusDotFill;
        
        #line default
        #line hidden
        
        
        #line 305 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.Effects.DropShadowEffect StatusGlow;
        
        #line default
        #line hidden
        
        
        #line 308 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 313 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTheme;
        
        #line default
        #line hidden
        
        
        #line 316 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ThemeIcon;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtStudioKey;
        
        #line default
        #line hidden
        
        
        #line 343 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSaveKey;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl ActiveLayersList;
        
        #line default
        #line hidden
        
        
        #line 404 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtNoLayers;
        
        #line default
        #line hidden
        
        
        #line 412 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPushDelta;
        
        #line default
        #line hidden
        
        
        #line 419 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkAutoPush;
        
        #line default
        #line hidden
        
        
        #line 422 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkAutoPull;
        
        #line default
        #line hidden
        
        
        #line 434 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkGhostCursors;
        
        #line default
        #line hidden
        
        
        #line 445 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl ConnectedUsersList;
        
        #line default
        #line hidden
        
        
        #line 464 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtNoUsers;
        
        #line default
        #line hidden
        
        
        #line 478 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl LogList;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FileCombo;
        
        #line default
        #line hidden
        
        
        #line 520 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPull;
        
        #line default
        #line hidden
        
        
        #line 523 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRefreshFiles;
        
        #line default
        #line hidden
        
        
        #line 528 "..\..\..\CadSyncControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSync;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.25.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/CadSyncPlugin;component/cadsynccontrol.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\CadSyncControl.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.25.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.StatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 2:
            this.StatusDotFill = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 3:
            this.StatusGlow = ((System.Windows.Media.Effects.DropShadowEffect)(target));
            return;
            case 4:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.BtnTheme = ((System.Windows.Controls.Button)(target));
            
            #line 314 "..\..\..\CadSyncControl.xaml"
            this.BtnTheme.Click += new System.Windows.RoutedEventHandler(this.BtnTheme_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ThemeIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.TxtStudioKey = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.BtnSaveKey = ((System.Windows.Controls.Button)(target));
            
            #line 346 "..\..\..\CadSyncControl.xaml"
            this.BtnSaveKey.Click += new System.Windows.RoutedEventHandler(this.BtnSaveKey_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ActiveLayersList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 10:
            this.TxtNoLayers = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.BtnPushDelta = ((System.Windows.Controls.Button)(target));
            
            #line 415 "..\..\..\CadSyncControl.xaml"
            this.BtnPushDelta.Click += new System.Windows.RoutedEventHandler(this.BtnPushDelta_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ChkAutoPush = ((System.Windows.Controls.CheckBox)(target));
            
            #line 421 "..\..\..\CadSyncControl.xaml"
            this.ChkAutoPush.Checked += new System.Windows.RoutedEventHandler(this.ChkAuto_Changed);
            
            #line default
            #line hidden
            
            #line 421 "..\..\..\CadSyncControl.xaml"
            this.ChkAutoPush.Unchecked += new System.Windows.RoutedEventHandler(this.ChkAuto_Changed);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ChkAutoPull = ((System.Windows.Controls.CheckBox)(target));
            
            #line 423 "..\..\..\CadSyncControl.xaml"
            this.ChkAutoPull.Checked += new System.Windows.RoutedEventHandler(this.ChkAuto_Changed);
            
            #line default
            #line hidden
            
            #line 423 "..\..\..\CadSyncControl.xaml"
            this.ChkAutoPull.Unchecked += new System.Windows.RoutedEventHandler(this.ChkAuto_Changed);
            
            #line default
            #line hidden
            return;
            case 14:
            this.ChkGhostCursors = ((System.Windows.Controls.CheckBox)(target));
            
            #line 440 "..\..\..\CadSyncControl.xaml"
            this.ChkGhostCursors.Checked += new System.Windows.RoutedEventHandler(this.ChkGhostCursors_Changed);
            
            #line default
            #line hidden
            
            #line 441 "..\..\..\CadSyncControl.xaml"
            this.ChkGhostCursors.Unchecked += new System.Windows.RoutedEventHandler(this.ChkGhostCursors_Changed);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ConnectedUsersList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 16:
            this.TxtNoUsers = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.LogList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 18:
            this.FileCombo = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 19:
            this.BtnPull = ((System.Windows.Controls.Button)(target));
            
            #line 522 "..\..\..\CadSyncControl.xaml"
            this.BtnPull.Click += new System.Windows.RoutedEventHandler(this.BtnPull_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.BtnRefreshFiles = ((System.Windows.Controls.Button)(target));
            
            #line 525 "..\..\..\CadSyncControl.xaml"
            this.BtnRefreshFiles.Click += new System.Windows.RoutedEventHandler(this.BtnRefreshFiles_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.BtnSync = ((System.Windows.Controls.Button)(target));
            
            #line 531 "..\..\..\CadSyncControl.xaml"
            this.BtnSync.Click += new System.Windows.RoutedEventHandler(this.BtnSync_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

